### ISSUE TITLE
Adding new software

### ISSUE THREAD

**Issue by tailaiw** [rob-med/awesome-TS-anomaly-detection#4]
I don't see a guide for contributors, so my apologies if this is not the preferred way to suggest a new item to the list.

I wanted to introduce [ADTK](https://www.github.com/arundo/adtk), a new Python package that we open-sourced recently. It is a framework for building rule-based/unsupervised anomaly detection models. It focuses on pragmatic pipelines of anomaly detection for real-world problems instead of implementation of new algorithms.

I tried to create a new branch and PR but it seems I don't have the permission.

Thank you!

**Comment by rob-med** [comment]
Hi @tailaiw, thanks for letting me know. This looks very useful! I'm adding it to the list.
